### ISSUE TITLE
Uncaught TypeError: class heritage events_1.EventEmitter is not an object or null

### ISSUE THREAD

**Issue by TYRANTHOSAURUS** [tiagosiebler/bitget-api#17]
Hi, im getting this error and its crashing my react app.

I wrapped the client inside a hook:

```
import {FuturesClient} from "bitget-api";
import {supabase} from "../supabase-client";
import {useAuth} from "../providers/user-provider";

export const useBitgetClient = (): FuturesClient => {
    const {user} = useAuth();
    const {data, error} = supabase
        .from("bitget_api")
        .select(`api_secret, api_phrase, api_key`)
        .eq("user_id", user?.id)
        .single();

    if (!data) {
        throw new Error("BitgetClient data not available");
    }

    const clientOptions = {
        apiKey: data.api_key,
        apiSecret: data.api_secret,
        apiPass: data.api_phrase
    };

    const bitgetClient = new FuturesClient(clientOptions);

    return bitgetClient;
};
```

And using it inside components like this:

```
 const history = useBitgetClient()
        .getRecentTrades("BTCUSDT_UMCBL")
        .then((r) => console.log("getHistoricTrades", r));

    console.log("history", history);
```
    
   When I start the app the app now crashes. After doing some research it turns out there's an issue with Vite which does automatically polyfill node.js modules.

From the [vite website](https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility):
    
**Module externalized for browser compatibility**

When you use a Node.js module in the browser, Vite will output the following warning.

    Module "fs" has been externalized for browser compatibility. Cannot access "fs.readFile" in client code.

This is because Vite does not automatically polyfill Node.js modules.

We recommend avoiding Node.js modules for browser code to reduce the bundle size, although you can add polyfills manually. If the module is imported from a third-party library (that's meant to be used in the browser), it's advised to report the issue to the respective library.

__________________________

Is there something else I can do until this has been improved? I'm kinda stuck for now not being able to access Bitget data.

Thanks

![Screenshot 2023-08-25 at 22 26 29](https://github.com/tiagosiebler/bitget-api/assets/120685196/b796d27b-3ca8-41bf-ae77-20587663be61)

**Comment by tiagosiebler** [comment]
Hi @TYRANTHOSAURUS 

There are two key dependencies that I'm aware of that have problems in the browser, since they're node modules:
- crypto (used for the hmac signature function as part of the request authentication process)
- events (EventEmitter is used to bubble up websocket events via the WS client)

Both have polyfills available, although I'm not familiar with Vite so can't provide specific guidance. I know that in typescript projects configured to build for frontend environments, you can install and then provide the polyfills in the tsconfig:
https://github.com/tiagosiebler/bybit-api#browser-usage

I'm not sure if the same method is enough with vite or if there's another way to correctly configure it, but hopefully this points you in the right direction! If this helps, can you let us know how you ended up configuring vite to correctly work with the polyfills? I'd love to document this better for others. Alternatively, if you still can't get it working after fighting it some more, please provide a very very minimal example project using this module and I can try to help.

**Comment by TYRANTHOSAURUS** [comment]
Hi @tiagosiebler ,

Thanks for the feedback,

In vite config pre-4.0 you could do something similar but that's not working for me anymore so I eventually found this package which did work.

Check out this package: https://github.com/davidmyersdev/vite-plugin-node-polyfills

Thanks!

**Comment by tiagosiebler** [comment]
Very useful, thank you! Would you mind sharing an example for others, on what you added to your vite.config when adding this package? Thanks!

**Comment by TYRANTHOSAURUS** [comment]
I got mine from the documentation:

```
import { resolve } from 'node:path'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'
import { nodePolyfills } from '../src/index'

export default defineConfig({
  plugins: [
    react(),
    nodePolyfills({
      include: ['fs', 'path', 'buffer'], // Add to include to import specific protocols
      exclude: ['fs'], // Add to exclude while leaving include empty to enable all then exclude.
      globals: {
        process: 'build',
      },
      protocolImports: true,
    }),
  ],
  root: resolve(__dirname),
})
```
